name: Cargo Check Each Crate

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  merge_group:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  cargo-check-each-crate-macos:
    # GitHub Actions allows using 'env' in a container context.
    # However, env variables don't work for forks: https://github.com/orgs/community/discussions/44322
    # This workaround sets the container image for each job using 'set-image' job output.
    # TODO: remove once migration is complete or this workflow is fully stable
    if: contains(github.event.label.name, 'GHA-migration') || contains(github.event.pull_request.labels.*.name, 'GHA-migration')
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        run: rustup toolchain install nightly
      - run: brew install protobuf
      - run: rustup target add wasm32-unknown-unknown --toolchain stable-aarch64-apple-darwin
      - run: rustup component add rust-src --toolchain stable-aarch64-apple-darwin
      - run: time cargo check --workspace --locked
